## PVC to be used for model storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-serving-ilab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
