FROM registry.redhat.io/ubi8/python-312:1@sha256:9fc882bb6d98ff5427e82f19c4b21202f25eb72d1acf7a98a12546c276ff224c

ARG SOURCE_CODE=.

# Default for ubi8/python
WORKDIR /opt/app-root/src/pipelines/distributed-ilab

COPY ${SOURCE_CODE} .

USER root

RUN echo "Installing Runtime Dependencies" && \
    dnf install -y skopeo && dnf clean all && \
    pip install --no-cache-dir -r requirements.txt && \
    chgrp -R 0 . && \
    chmod -R g=u . && \
    mv mixtral-tokenizer /models

USER default

# Default for ubi8/python
WORKDIR /opt/app-root/src

LABEL name="odh-ml-pipelines-runtime-generic" \
    com.redhat.component="odh-ml-pipelines-runtime-generic-container" \
    summary="Generic runtime image for pipeline tasks with embedded managed pipelines." \
    description="Generic runtime image for pipeline tasks with embedded managed pipelines." \
    summary="odh-ml-pipelines-runtime-generic" \
    maintainer="['managed-open-data-hub@redhat.com']" \
    io.openshift.expose-services="" \
    io.k8s.display-name="odh-ml-pipelines-runtime-generic" \
    io.k8s.description="odh-ml-pipelines-runtime-generic"
